spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/pp
      username: matthew
      password: matthew
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
